# Generated by Django 4.1.7 on 2023-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_player_id_contact_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='player_id',
            field=models.CharField(default='4', max_length=255),
            preserve_default=False,
        ),
    ]
