# Generated by Django 4.2.1 on 2023-05-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designation',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='facebook_link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter_link',
        ),
    ]
