# Generated by Django 4.2.1 on 2023-05-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_designation_team_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Member',
        ),
    ]
