# Generated by Django 4.2.1 on 2023-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('current_position', models.CharField(choices=[('TOP', 'Top'), ('JUG', 'jungle'), ('MID', 'middle'), ('BOT', 'bottom'), ('SUP', 'support')])),
                ('photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('current_team', models.CharField(choices=[('RNG', 'Royal Never Give Up'), ('EDG', 'Edward Gaming Hycan'), ('WE', 'Team WE'), ('IG', 'Invictus Gaming'), ('TES', 'Top Esports'), ('FPX', 'FunPlus Phoenix'), ('OMG', 'Oh My God'), ('JDG', 'JDG Intel Esports Club'), ('BLG', 'Bilibili Gaming'), ('WBG', 'Weibo Gaming')])),
                ('first_show_year', models.IntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
