# Generated by Django 4.2.1 on 2023-05-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_retire',
            field=models.BooleanField(default=False),
        ),
    ]
