# Generated by Django 4.2.1 on 2023-05-18 18:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_is_retire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='current_team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=ckeditor.fields.RichTextField(default='lpl player'),
        ),
    ]
