# Generated by Django 4.2.1 on 2023-05-18 22:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_current_position_player_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='honor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('WORLD', 'World Champion'), ('MSI', 'Mid-Season Invitational Champion'), ('LPL', 'LPL Championship'), ('Demacia', 'Demacia Cup Championship')], default=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_show_year',
            field=models.IntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TOP', 'Top'), ('JUG', 'jungle'), ('MID', 'middle'), ('BOT', 'bottom'), ('SUP', 'support')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RNG', 'Royal Never Give Up'), ('EDG', 'Edward Gaming Hycan'), ('WE', 'Team WE'), ('IG', 'Invictus Gaming'), ('TES', 'Top Esports'), ('FPX', 'FunPlus Phoenix'), ('OMG', 'Oh My God'), ('JDG', 'JDG Intel Esports Club'), ('BLG', 'Bilibili Gaming'), ('WBG', 'Weibo Gaming')], max_length=100),
        ),
    ]
